spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:testdb
    username: sa
    password: